import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { describe, expect, it } from "vitest";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function read(filePath: string) {
  return fs.readFileSync(path.join(root, filePath), "utf8");
}

describe("package layout", () => {
  it("declares a Formax plugin manifest for the packaged runtime", () => {
    const manifest = JSON.parse(read(".formax-plugin/plugin.json"));

    expect(manifest.name).toBe("formax-chrome");
    expect(manifest.runtime.browserClient).toBe("scripts/browser-client.mjs");
    expect(manifest.runtime.mcpServer).toBe("mcp-node-repl/server.js");
    expect(manifest.runtime.nativeHost).toBe("extension-host/<platform>/<arch>/extension-host");
    expect(manifest.skills).toEqual([
      {
        name: "control-chrome",
        path: "skills/control-chrome/SKILL.md",
      },
    ]);
    expect(manifest.docs).toBe("docs");
  });

  it("exposes the stable packaged browser client entrypoint", async () => {
    const moduleUrl = pathToFileURL(path.join(root, "scripts/browser-client.mjs")).href;
    const browserClient = await import(moduleUrl);
    const source = read("scripts/browser-client.mjs");

    expect(browserClient.setupBrowserRuntime).toEqual(expect.any(Function));
    expect(source).toContain("Generated by scripts/build-browser-client.js");
    expect(source).not.toContain('export * from "../mcp-node-repl/browser-client.js";');
  });

  it("bundles the MCP runtime entrypoints into self-contained files", () => {
    const serverSource = read("mcp-node-repl/server.js");
    const kernelChildSource = read("mcp-node-repl/kernel-child.js");

    expect(serverSource).toContain("Generated by scripts/build-mcp-node-repl.js");
    expect(serverSource).not.toContain('from "@modelcontextprotocol/sdk/server/mcp.js"');
    expect(serverSource).not.toContain('from "@modelcontextprotocol/sdk/server/stdio.js"');
    expect(serverSource).not.toContain('from "zod/v4"');
    expect(kernelChildSource).toContain("Generated by scripts/build-mcp-node-repl.js");
  });

  it("keeps package and install scripts aligned with the plugin-like layout", () => {
    const packageDist = read("scripts/package-dist.js");
    const packageJson = JSON.parse(read("package.json"));
    const installer = read("scripts/install-formax-runtime.js");
    const extensionIds = read("scripts/extension-ids.js");

    for (const artifact of [
      ".formax-plugin",
      "docs",
      "scripts/browser-client.mjs",
      "scripts/formax-doctor.js",
      "scripts/formax-uninstall.js",
      "skills/control-chrome/SKILL.md",
    ]) {
      expect(packageDist).toContain(artifact);
    }

    for (const artifact of [
      ".formax-plugin",
      "docs",
      "scripts/browser-client.mjs",
      "scripts/formax-doctor.js",
      "scripts/formax-uninstall.js",
      "skills",
    ]) {
      expect(installer).toContain(artifact);
    }

    expect(installer).toContain("formax-browser-mcp");
    expect(installer).toContain("formax-doctor");
    expect(installer).toContain("formax-uninstall");
    expect(installer).toContain("runtime is self-contained");
    expect(installer).toContain("rewriteInstalledPackage");
    expect(installer).toContain("rewriteInstalledConfig");
    expect(installer).not.toContain('["node_modules", "node_modules"]');
    expect(extensionIds).toContain('export const WEB_STORE_EXTENSION_ID = "dchkbbjmkheilkmencpckilhmmcppdne";');
    expect(extensionIds).toContain('export const DEV_EXTENSION_ID = "hooonkcoopaigliifkabcdjfmjjffmbm";');
    expect(packageDist).not.toContain("--dist-dir");
    expect(packageDist).not.toContain("rewriteLocalTestingConfig");
    expect(packageJson.scripts["install:formax-runtime:dev"]).toContain("$HOME/.formax-dev");
    expect(packageJson.scripts["install:formax-runtime:dev"]).toContain("--extension-id dev");
    expect(packageJson.scripts["test:real"]).toContain("run-real-browser-test.js");
    expect(packageJson.scripts["test:real-sites"]).toContain("run-real-browser-test.js");
  });

  it("packages only the bundled browser client entrypoint for runtime distribution", () => {
    const distRoot = path.join(root, "dist");

    expect(fs.existsSync(path.join(distRoot, "scripts", "browser-client.mjs"))).toBe(true);
    expect(fs.existsSync(path.join(distRoot, "mcp-node-repl", "browser-client.js"))).toBe(false);
    expect(fs.existsSync(path.join(distRoot, "mcp-node-repl", "kernel.js"))).toBe(false);
    expect(fs.existsSync(path.join(distRoot, "skill"))).toBe(false);
    expect(fs.existsSync(path.join(distRoot, "skills", "control-chrome", "SKILL.md"))).toBe(true);
  });
});
